<a href="https://colab.research.google.com/github/sayam-h069/2403A51L27_B51_PDS/blob/main/Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Question 1
import numpy as np

A = np.random.randint(1, 11, size=(3, 3))
B = np.random.randint(1, 11, size=(3, 3))

add_result = np.add(A, B)
sub_result = np.subtract(A, B)

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)
print("\nA + B:\n", add_result)
print("\nA - B:\n", sub_result)

print("\nVerification for element [0,0]:")
print(f"A[0,0] = {A[0,0]}, B[0,0] = {B[0,0]}")
print(f"Addition: {A[0,0]} + {B[0,0]} = {add_result[0,0]}")
print(f"Subtraction: {A[0,0]} - {B[0,0]} = {sub_result[0,0]}")

print("\nNote: Broadcasting is not used here since both matrices are of the same shape (3x3).")

Matrix A:
 [[ 1  1  1]
 [ 1  5 10]
 [ 5  6  6]]

Matrix B:
 [[1 8 7]
 [2 3 8]
 [3 9 6]]

A + B:
 [[ 2  9  8]
 [ 3  8 18]
 [ 8 15 12]]

A - B:
 [[ 0 -7 -6]
 [-1  2  2]
 [ 2 -3  0]]

Verification for element [0,0]:
A[0,0] = 1, B[0,0] = 1
Addition: 1 + 1 = 2
Subtraction: 1 - 1 = 0

Note: Broadcasting is not used here since both matrices are of the same shape (3x3).


In [3]:
#Question 2
import numpy as np

A = np.random.randint(1, 10, size=(3, 2))
B = np.random.randint(1, 10, size=(2, 3))

result = np.dot(A, B)

print("Matrix A (3x2):\n", A)
print("\nMatrix B (2x3):\n", B)
print("\nDot Product (A @ B):\n", result)

print("\nVerification for element [0,0]:")
calc = A[0,0]*B[0,0] + A[0,1]*B[1,0]
print(f"Manual: {A[0,0]}*{B[0,0]} + {A[0,1]}*{B[1,0]} = {calc}")
print(f"Dot Product Result[0,0] = {result[0,0]}")

transformation = np.array([[1, 0, 1],
                           [0, 1, 1],
                           [0, 0, 1]])
image_vector = np.array([[2, 3, 1]]).T
transformed = np.dot(transformation, image_vector)

print("\nTransformation Matrix:\n", transformation)
print("\nImage Vector:\n", image_vector)
print("\nTransformed Vector:\n", transformed)

Matrix A (3x2):
 [[6 6]
 [6 9]
 [7 2]]

Matrix B (2x3):
 [[1 8 2]
 [4 6 2]]

Dot Product (A @ B):
 [[ 30  84  24]
 [ 42 102  30]
 [ 15  68  18]]

Verification for element [0,0]:
Manual: 6*1 + 6*4 = 30
Dot Product Result[0,0] = 30

Transformation Matrix:
 [[1 0 1]
 [0 1 1]
 [0 0 1]]

Image Vector:
 [[2]
 [3]
 [1]]

Transformed Vector:
 [[3]
 [4]
 [1]]
